lunchmap/urls.py
from django.urls import path
from . import views

app_name = 'lunchmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('lunchmap/', include('lunchmap.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/lunchmap/')),
]

lunchmap/models.py
from django.db import models

# カテゴリーテーブルを作成する
class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# ショップテーブルを作成する
class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

lunchmap/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Category, Shop

# クラスベース
class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    model = Shop

lunchmap/templates/lunchmap/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <!-- bootstrap4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>body {padding-top: 80px;}</style>
</head>
<body>
    <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
        <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Lunchmap</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

lunchmap/templates/lunchmap/shop_detail.html
{% extends "./base.html"%}
{% block title %}lunchmap{% endblock %}
{% block content %}
    <h1>{{ shop.name }}</h1>
    <div>
        <p>{{ shop.category.name }}</p>
        <p>{{ shop.address }}</p>
    </div>
    <div>
        <a href='{% url "lunchmap:index" %}'>一覧</a>
    </div>
    
{% endblock %}

lunchmap/templates/lunchmap/shop_list.html
{% extends "./base.html"%}
{% block title %}lunchmap{% endblock %}
{% block content %}
    <h1>お店一覧</h1>

    <table class='table table-striped table-hover'>
        <tr>
            <th>カテゴリ</th><th>店名</th><th>住所</th>
        </tr>
        {% for shop in object_list %}
        <tr>
            <td>{{ shop.category.name }}</td>
            <td><a href='{% url "lunchmap:detail" shop.pk %}'>{{ shop.name }}</a></td>
            <td>{{ shop.address }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}